---
# This playbook deploys the whole MEAN application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  remote_user: vagrant
  sudo: yes
  vars_files:
    - vars/all
  roles:
    - common

- name: configure and deploy the webservers and application code
  #hosts: webservers
  hosts: all
  remote_user: vagrant
  sudo: yes
  vars_files:
    - vars/all
    - vars/nodeserver
  roles:
    - nodeserver

- name: deploy MySQL and configure the databases
  #hosts: dbservers
  hosts: all
  remote_user: vagrant
  sudo: yes
  vars_files:
    - vars/all
    - vars/mongodb
  roles:
    - mongodb
