---
# This playbook deploys the whole LAMP application stack in this site.  

- name: Install WordPress, MySQL, Apache, and PHP-FPM
  hosts: wordpress-centos
  remote_user: vagrant
  # remote_user: user
  sudo: yes

  vars:
    ntpserver: es.pool.ntp.org
    wp_version: 4.3
    wp_sha256sum: 3b0db3abe8504f15a33cf64188a493ec0de01eaa8d20e37c3d6a1d9fa0a40fb4
    wp_db_name: wordpress
    wp_db_user: wordpress
    wp_db_password: secret
    mysql_port: 3306
    server_hostname: www.example1.com
    auto_up_disable: false
    core_update_level: true
    repository: https://github.com/bennojoy/mywebapp.git
    httpd_port: 80
    mysqlservice: mysqld
    mysql_port: 3306
    dbuser: foouser
    dbname: foodb
    upassword: abc
  roles:
    - common
    - db
    - web
    - php-fpm
    - wordpress