---
# This playbook deploys the whole LAMP application stack in this site.  

- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: wordpress-centos
  remote_user: vagrant
  # remote_user: user
  sudo: yes

  vars:
    ntpserver: es.pool.ntp.org
    wp_version: 4.2.4
    wp_sha256sum: 42ca594afc709cbef8528a6096f5a1efe96dcf3164e7ce321e87d57ae015cc82
    wp_db_name: wordpress
    wp_db_user: wordpress
    wp_db_password: secret
    mysql_port: 3306
    server_hostname: www.example1.com
    auto_up_disable: false
    core_update_level: true
    repository: https://github.com/bennojoy/mywebapp.git
    httpd_port: 80
    mysqlservice: mysqld
    mysql_port: 3306
    dbuser: foouser
    dbname: foodb
    upassword: abc
  roles:
    - common
    - db
    - web
    - php-fpm
    - wordpress