- name: fetch influxdb
  get_url: url=https://s3.amazonaws.com/influxdb/influxdb-0.9.2-1.x86_64.rpm dest=/tmp/influxdb-0.9.2-1.x86_64.rpm

- name: install influxdb
  shell: rpm -i /tmp/influxdb-0.9.2-1.x86_64.rpm

- name: setup influxdb service
  service: name=influxdb state=started enabled=yes

- name: wait 10 seconds for the service get up
  shell: sleep 10

- name: setup databases
  shell: "curl -X POST 'http://localhost:8086/db?u={{ influxdb.username }}&p={{ influxdb.password }}' -d '{\"name\": \"{{ item }}\"}'"
  with_items: 
    - "{{ influxdb.dbname }}"
    - "{{ grafana.dbname }}"

