- name: install python-related packages cetos/7
  yum: name={{ item }} state=installed
  with_items:
    - python
    - python-devel
    - python-setuptools

- name: install pip
  easy_install: name=pip

- name: install virtualenv
  pip: name=virtualenv
