# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "influxdb-grafana-centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.box_url = "http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7.box"
    centos.vm.network :private_network, ip: "192.168.33.21"
    centos.vm.provision "ansible" do |ansible| 
      ansible.playbook = "ansible/playbook.yml"
    end 
  end

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "1024"]
  end

end
