# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "lamp-centos" do |centos|
    centos.vm.box = "centos7-base"
    centos.vm.box_url = "https://github.com/holms/vagrant-centos7-box/releases/download/7.1.1503.001/CentOS-7.1.1503-x86_64-netboot.box"
    centos.vm.network "forwarded_port", guest: 80, host: 8080
    centos.vm.network "private_network", ip: "192.168.33.10"
    centos.vm.synced_folder "./share", "/vagrant_share"
    centos.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
    end
  end
  # Enable provisioning with Ansible
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "./ansible/playbook.yml"
    ansible.inventory_path = "./ansible/inventory"
    #ansible.inventory_path = ".vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory"
    # bug on playbook flags
    ansible.extra_vars = { ansible_ssh_user: 'vagrant',
                           ansible_ssh_host: '127.0.0.1',
                           ansible_ssh_port: '2222' }
  end
end
